#!/usr/bin/env bash
master=${master-master}

branch=$(git rev-parse --abbrev-ref HEAD)
git co - > /dev/null
lastBranch=$(git rev-parse --abbrev-ref HEAD)
git co $branch > /dev/null
git co $master > /dev/null
git diff ...$branch $@
git co $lastBranch > /dev/null
git co $branch > /dev/null
