#!/usr/bin/env perl
# 
# prints stats on a list of numbers
#
# broken up from http://stackoverflow.com/questions/9789806/command-line-utility-to-print-statistics-of-numbers-in-linux

use List::Util qw(max min sum);
@a=();
while(<>){
	$sqsum+=$_*$_;
	chomp;
	push(@a,$_)
}
$n=@a;
$s=sum(@a);
$a=$s/@a;
$m=max(@a);
$mm=min(@a);
$std=sqrt($sqsum/$n-($s/$n)*($s/$n));
$mid=int @a/2;
@srtd=sort @a;
if(@a%2){
	$med=$srtd[$mid];
}else{
	$med=($srtd[$mid-1]+$srtd[$mid])/2;
}
print "n: $n\nsum: $s\navg: $a\nstd: $std\nmed: $med\nmax: $m\nmin: $mm\n";
