#!/usr/bin/env perl

for my $f (<>){
	print "$f";
	if($f !~ m#\.spec\.js# && $f =~ m#(.*)ui/(.*)\.js#){
		$f =~ s#(.*)ui/(.*)\.js#$1coverage/PhantomJS\\ 1.9.8\\ \\(Mac\\ OS\\ X\\ 0.0.0\\)/$2.js.html#;
		`open $f`;
	}
}

